In [257]:
import pandas as pd

In [258]:
pip install pandas


Note: you may need to restart the kernel to use updated packages.


In [259]:
df= pd.read_csv("https://raw.githubusercontent.com/shsarv/Machine-Learning-Projects/main/Diabetes%20Prediction%20%5BEND%202%20END%5D/dataset/kaggle_diabetes.csv")

In [260]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0               2      138             62             35        0  33.6   
1               0       84             82             31      125  38.2   
2               0      145              0              0        0  44.2   
3               0      135             68             42      250  42.3   
4               1      139             62             41      480  40.7   
...           ...      ...            ...            ...      ...   ...   
1995            2       75             64             24       55  29.7   
1996            8      179             72             42      130  32.7   
1997            6       85             78              0        0  31.2   
1998            0      129            110             46      130  67.1   
1999            2       81             72             15       76  30.1   

      DiabetesPedigreeFunction  Age  Outcome  
0                        0.127   47        1  
1                        0.233   23        0  
2                        0.630   31        1  
3                        0.365   24        1  
4                        0.536   21        0  
...                        ...  ...      ...  
1995                     0.370   33        0  
1996                     0.719   36        1  
1997                     0.382   42        0  
1998                     0.319   26        1  
1999                     0.547   25        0  

[2000 rows x 9 columns]

In [261]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [262]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [263]:
from sklearn.model_selection import train_test_split

In [264]:
pip install sklearn

  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
Note: you may need to restart the kernel to use updated packages.


  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-

In [265]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [266]:
y=df['Outcome']
x=df.drop('Outcome',axis=1)

In [267]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [268]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [269]:
lr = LogisticRegression()
dr = DecisionTreeClassifier()

In [270]:
lr.fit(x_train,y_train)
dr.fit(x_train,y_train)

c:\Users\bhagy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [271]:
print(lr.score(x_train,y_train))

0.768


In [272]:
print("logistic",lr.score(x_train,y_train),lr.score(x_test,y_test))

logistic 0.768 0.794


In [273]:
print("decision tree",dr.score(x_train,y_train),dr.score(x_test,y_test))

decision tree 1.0 0.966


In [274]:
from sklearn.model_selection import cross_val_score

In [275]:
cross_val_score(lr,x_test,y_test,cv=5)

c:\Users\bhagy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\bhagy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

array([0.74, 0.83, 0.8 , 0.78, 0.81])

In [276]:
cross_val_score(lr,x_train,y_train,cv=5)

c:\Users\bhagy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\bhagy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

array([0.76333333, 0.78333333, 0.79333333, 0.76666667, 0.73      ])

In [277]:
 cross_val_score(dr,x_test,y_test,cv=5)

array([0.72, 0.73, 0.87, 0.8 , 0.77])

In [278]:
cross_val_score(dr,x_train,y_train,cv=5)

array([0.92666667, 0.93333333, 0.95333333, 0.96666667, 0.93333333])

In [279]:
from sklearn.model_selection import GridSearchCV

In [280]:
param_grid = {
    'C' : [0.1,1,10,100],           #regularisation parameter
    'penalty':['l2','l1'],   #penalty types
    'solver':['liblinear']  # Optimization algorithm
}

In [281]:
#Setup GridSearch with cross-val 
grid_search = GridSearchCV(estimator = lr,param_grid=param_grid,cv=5,scoring='accuracy')

In [282]:
#fit the model with the training data
grid_search.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.1, 1, 10, 100], 'penalty': ['l2', 'l1'],
                         'solver': ['liblinear']},
             scoring='accuracy')

In [283]:
#best hyperparametry found
best_params = grid_search.best_params_
print("Best Parameters:",best_params)

Best Parameters: {'C': 1, 'penalty': 'l2', 'solver': 'liblinear'}


In [284]:
lr= LogisticRegression(max_iter=1000,C=10,penalty='l1',solver='liblinear')

In [285]:
lr.fit(x_train,y_train)

LogisticRegression(C=10, max_iter=1000, penalty='l1', solver='liblinear')

In [286]:
lr.score(x_test,y_test)

0.794

In [287]:
grid_search.score(x_test,y_test)

0.79

In [288]:
from sklearn.metrics import classification_report

In [289]:
print(classification_report(y_test,lr.predict(x_test)))

              precision    recall  f1-score   support

           0       0.80      0.91      0.85       320
           1       0.78      0.59      0.68       180

    accuracy                           0.79       500
   macro avg       0.79      0.75      0.76       500
weighted avg       0.79      0.79      0.79       500



In [290]:
from sklearn.metrics import confusion_matrix

In [291]:
confusion_matrix(y_true=[1,0,1,0,1,1],y_pred=[1,0,0,0,0,1])

array([[2, 0],
       [2, 2]])

In [292]:
confusion_matrix(y_test,lr.predict(x_test))

array([[290,  30],
       [ 73, 107]])

In [293]:
import numpy as np

In [294]:
for i in df.columns:
    print(df[np.isinf(df[i])])
    time.sleep(5)

Empty DataFrame
Columns: [Pregnancies, Glucose, BloodPressure, SkinThickness, Insulin, BMI, DiabetesPedigreeFunction, Age, Outcome]
Index: []


NameError: name 'time' is not defined

In [166]:
recall=107/(107+73)
recall

0.5944444444444444

In [167]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

print(confusion_matrix(y_test,lr.predict(x_test)))
print(accuracy_score(y_test,lr.predict(x_test)))
print(precision_score(y_test,lr.predict(x_test)))
print(recall_score(y_test,lr.predict(x_test)))
print(f1_score(y_test,lr.predict(x_test)))

[[290  30]
 [ 73 107]]
0.794
0.781021897810219
0.5944444444444444
0.6750788643533123


In [168]:
import pickle
with open("model.pickle","wb") as model_file:
    pickle.dump(lr,model_file)

project start

In [169]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0               2      138             62             35        0  33.6   
1               0       84             82             31      125  38.2   
2               0      145              0              0        0  44.2   
3               0      135             68             42      250  42.3   
4               1      139             62             41      480  40.7   
...           ...      ...            ...            ...      ...   ...   
1995            2       75             64             24       55  29.7   
1996            8      179             72             42      130  32.7   
1997            6       85             78              0        0  31.2   
1998            0      129            110             46      130  67.1   
1999            2       81             72             15       76  30.1   

      DiabetesPedigreeFunction  Age  Outcome  
0                        0.127   47        1  
1                        0.233   23        0  
2                        0.630   31        1  
3                        0.365   24        1  
4                        0.536   21        0  
...                        ...  ...      ...  
1995                     0.370   33        0  
1996                     0.719   36        1  
1997                     0.382   42        0  
1998                     0.319   26        1  
1999                     0.547   25        0  

[2000 rows x 9 columns]

In [170]:
df['BloodPressure'].value_counts()

BloodPressure
74     145
70     144
78     128
68     125
64     120
72     118
80      98
62      94
76      93
60      92
0       90
82      83
88      67
66      65
84      61
90      55
58      54
86      53
50      31
56      31
54      31
52      29
75      20
65      19
94      18
85      14
48      13
92      12
44      11
106      9
100      9
98       8
96       8
110      7
46       6
104      5
108      5
55       4
61       4
114      3
102      3
30       3
122      3
38       3
95       2
24       2
40       2
Name: count, dtype: int64

In [171]:
df['SkinThickness'].value_counts()

SkinThickness
0      573
32      83
30      75
23      60
27      58
18      54
28      54
39      52
33      51
31      50
25      47
37      45
22      44
29      44
40      42
41      41
19      41
17      41
26      39
36      38
15      33
35      33
20      32
24      31
42      31
13      30
21      27
46      25
12      21
34      19
38      18
16      15
14      15
43      15
11      14
45      13
10      13
48      12
44      12
49      11
47       7
50       7
8        6
52       4
54       4
63       3
51       3
56       3
7        3
60       2
99       2
59       2
110      2
Name: count, dtype: int64

In [172]:
df['SkinThickness'].max()

np.int64(110)

In [173]:
df['Glucose'].max()

np.int64(199)

In [174]:
df['BMI'].max()

np.float64(80.6)

In [175]:
df['Glucose'].value_counts()

Glucose
99     49
100    44
102    39
129    37
106    36
       ..
177     2
191     2
67      2
186     2
198     2
Name: count, Length: 136, dtype: int64

In [176]:
df['DiabetesPedigreeFunction'].value_counts()

DiabetesPedigreeFunction
0.258    16
0.207    15
0.268    13
0.261    13
0.520    13
         ..
0.720     2
0.322     2
0.320     2
0.493     1
0.107     1
Name: count, Length: 505, dtype: int64

In [177]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0               2      138             62             35        0  33.6   
1               0       84             82             31      125  38.2   
2               0      145              0              0        0  44.2   
3               0      135             68             42      250  42.3   
4               1      139             62             41      480  40.7   
...           ...      ...            ...            ...      ...   ...   
1995            2       75             64             24       55  29.7   
1996            8      179             72             42      130  32.7   
1997            6       85             78              0        0  31.2   
1998            0      129            110             46      130  67.1   
1999            2       81             72             15       76  30.1   

      DiabetesPedigreeFunction  Age  Outcome  
0                        0.127   47        1  
1                        0.233   23        0  
2                        0.630   31        1  
3                        0.365   24        1  
4                        0.536   21        0  
...                        ...  ...      ...  
1995                     0.370   33        0  
1996                     0.719   36        1  
1997                     0.382   42        0  
1998                     0.319   26        1  
1999                     0.547   25        0  

[2000 rows x 9 columns]

In [299]:
zero_counts=(df==0).sum()
print(zero_counts)

Pregnancies                  301
Glucose                       13
BloodPressure                 90
SkinThickness                573
Insulin                      956
BMI                           28
DiabetesPedigreeFunction       0
Age                            0
Outcome                     1316
dtype: int64


In [300]:
df['BloodPressure']=df['BloodPressure'].replace(0,df['BloodPressure'].mean())

In [301]:
df['BloodPressure']

0        62.0000
1        82.0000
2        69.1455
3        68.0000
4        62.0000
          ...   
1995     64.0000
1996     72.0000
1997     78.0000
1998    110.0000
1999     72.0000
Name: BloodPressure, Length: 2000, dtype: float64

In [302]:
df['BMI']=df['BMI'].replace(0,df['BMI'].mean())

In [303]:
df['BMI']

0       33.6
1       38.2
2       44.2
3       42.3
4       40.7
        ... 
1995    29.7
1996    32.7
1997    31.2
1998    67.1
1999    30.1
Name: BMI, Length: 2000, dtype: float64

through mean

In [304]:
df['SkinThickness']=df['SkinThickness'].replace(0,df['SkinThickness'].mean())

In [305]:
df['SkinThickness']

0       35.000
1       31.000
2       20.935
3       42.000
4       41.000
         ...  
1995    24.000
1996    42.000
1997    20.935
1998    46.000
1999    15.000
Name: SkinThickness, Length: 2000, dtype: float64

In [306]:
zero_counts=(df==0).sum()
print(zero_counts)

Pregnancies                  301
Glucose                       13
BloodPressure                  0
SkinThickness                  0
Insulin                      956
BMI                            0
DiabetesPedigreeFunction       0
Age                            0
Outcome                     1316
dtype: int64


In [307]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure               float64
SkinThickness               float64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [308]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0               2      138        62.0000         35.000        0  33.6   
1               0       84        82.0000         31.000      125  38.2   
2               0      145        69.1455         20.935        0  44.2   
3               0      135        68.0000         42.000      250  42.3   
4               1      139        62.0000         41.000      480  40.7   
...           ...      ...            ...            ...      ...   ...   
1995            2       75        64.0000         24.000       55  29.7   
1996            8      179        72.0000         42.000      130  32.7   
1997            6       85        78.0000         20.935        0  31.2   
1998            0      129       110.0000         46.000      130  67.1   
1999            2       81        72.0000         15.000       76  30.1   

      DiabetesPedigreeFunction  Age  Outcome  
0                        0.127   47        1  
1                        0.233   23        0  
2                        0.630   31        1  
3                        0.365   24        1  
4                        0.536   21        0  
...                        ...  ...      ...  
1995                     0.370   33        0  
1996                     0.719   36        1  
1997                     0.382   42        0  
1998                     0.319   26        1  
1999                     0.547   25        0  

[2000 rows x 9 columns]

Project

In [331]:
y=df['Outcome']
x=df.drop('Outcome',axis=1)

In [332]:
from sklearn.model_selection import train_test_split

In [333]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [334]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [335]:
lr = LogisticRegression()
dr = DecisionTreeClassifier()

In [336]:
lr.fit(x_train,y_train)
dr.fit(x_train,y_train)

c:\Users\bhagy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [337]:
print(lr.score(x_train,y_train),lr.score(x_test,y_test))

0.764 0.786


In [338]:
print("logistic",lr.score(x_train,y_train),lr.score(x_test,y_test))
print("decision tree",dr.score(x_train,y_train),dr.score(x_test,y_test))

logistic 0.764 0.786
decision tree 1.0 0.966


In [339]:
from sklearn.model_selection import cross_val_score

In [340]:
cross_val_score(lr,x_train,y_train,cv=5)

c:\Users\bhagy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\bhagy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/st

array([0.76333333, 0.78333333, 0.76666667, 0.76666667, 0.71666667])

In [341]:
cross_val_score(dr,x_test,y_test,cv=5)

array([0.75, 0.75, 0.9 , 0.84, 0.82])

In [342]:
x_test

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
1860            4      111        72.0000         47.000      207  37.1   
353             1       90        62.0000         12.000       43  27.2   
1333            8      179        72.0000         42.000      130  32.7   
905             0      141        69.1455         20.935        0  42.4   
1289            9      122        56.0000         20.935        0  33.3   
...           ...      ...            ...            ...      ...   ...   
765             5      121        72.0000         23.000      112  26.2   
1356            4      109        64.0000         44.000       99  34.8   
408             8      197        74.0000         20.935        0  25.9   
1614            5      158        70.0000         20.935        0  29.8   
694             2       90        60.0000         20.935        0  23.5   

      DiabetesPedigreeFunction  Age  
1860                     1.390   56  
353                      0.580   24  
1333                     0.719   36  
905                      0.205   29  
1289                     1.114   33  
...                        ...  ...  
765                      0.245   30  
1356                     0.905   26  
408                      1.191   39  
1614                     0.207   63  
694                      0.191   25  

[500 rows x 8 columns]

In [344]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0               2      138        62.0000         35.000        0  33.6   
1               0       84        82.0000         31.000      125  38.2   
2               0      145        69.1455         20.935        0  44.2   
3               0      135        68.0000         42.000      250  42.3   
4               1      139        62.0000         41.000      480  40.7   
...           ...      ...            ...            ...      ...   ...   
1995            2       75        64.0000         24.000       55  29.7   
1996            8      179        72.0000         42.000      130  32.7   
1997            6       85        78.0000         20.935        0  31.2   
1998            0      129       110.0000         46.000      130  67.1   
1999            2       81        72.0000         15.000       76  30.1   

      DiabetesPedigreeFunction  Age  Outcome  
0                        0.127   47        1  
1                        0.233   23        0  
2                        0.630   31        1  
3                        0.365   24        1  
4                        0.536   21        0  
...                        ...  ...      ...  
1995                     0.370   33        0  
1996                     0.719   36        1  
1997                     0.382   42        0  
1998                     0.319   26        1  
1999                     0.547   25        0  

[2000 rows x 9 columns]

In [345]:
df.dtypes

Pregnancies                   int64
Glucose                       int64
BloodPressure               float64
SkinThickness               float64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [328]:
zero_counts=(df==0).sum()
print(zero_counts)

Pregnancies                  301
Glucose                       13
BloodPressure                  0
SkinThickness                  0
Insulin                      956
BMI                            0
DiabetesPedigreeFunction       0
Age                            0
Outcome                     1316
dtype: int64


In [329]:
x_test

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
1860            4      111        72.0000         47.000      207  37.1   
353             1       90        62.0000         12.000       43  27.2   
1333            8      179        72.0000         42.000      130  32.7   
905             0      141        69.1455         20.935        0  42.4   
1289            9      122        56.0000         20.935        0  33.3   
...           ...      ...            ...            ...      ...   ...   
765             5      121        72.0000         23.000      112  26.2   
1356            4      109        64.0000         44.000       99  34.8   
408             8      197        74.0000         20.935        0  25.9   
1614            5      158        70.0000         20.935        0  29.8   
694             2       90        60.0000         20.935        0  23.5   

      DiabetesPedigreeFunction  Age  
1860                     1.390   56  
353                      0.580   24  
1333                     0.719   36  
905                      0.205   29  
1289                     1.114   33  
...                        ...  ...  
765                      0.245   30  
1356                     0.905   26  
408                      1.191   39  
1614                     0.207   63  
694                      0.191   25  

[500 rows x 8 columns]

In [343]:
x_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
1738            1       91           54.0         25.000      100  25.2   
548             1      164           82.0         43.000       67  32.8   
936             0       74           52.0         10.000       36  27.8   
1389            6      134           80.0         37.000      370  46.2   
1607            3       90           78.0         20.935        0  42.7   
...           ...      ...            ...            ...      ...   ...   
1130            3      123          100.0         35.000      240  57.3   
1294            0      100           70.0         26.000       50  30.8   
860             1      100           66.0         29.000      196  32.0   
1459            4       95           64.0         20.935        0  32.0   
1126            9      154           78.0         30.000      100  30.9   

      DiabetesPedigreeFunction  Age  
1738                     0.234   23  
548                      0.341   50  
936                      0.269   22  
1389                     0.238   46  
1607                     0.559   21  
...                        ...  ...  
1130                     0.880   22  
1294                     0.597   21  
860                      0.444   42  
1459                     0.161   31  
1126                     0.164   45  

[1500 rows x 8 columns]

In [346]:
lr.score(x_test,y_test)

0.786

In [347]:
from sklearn.model_selection import GridSearchCV

In [351]:
#Setup GridSearch with cross-val 
grid_search = GridSearchCV(estimator = lr,param_grid=param_grid,cv=5,scoring='accuracy')

#fit the model with the training data
grid_search.fit(x_train,y_train)

#best hyperparametry found
best_params = grid_search.best_params_
print("Best Parameters:",best_params)

Best Parameters: {'C': 1, 'penalty': 'l2', 'solver': 'liblinear'}


In [362]:
grid_search.score(x_test,y_test)

0.776

In [363]:
from sklearn.impute import KNNImputer

In [364]:
kn=KNNImputer(n_neighbors=3)

In [365]:
df=pd.read_csv('https://raw.githubusercontent.com/shsarv/Machine-Learning-Projects/main/Diabetes%20Prediction%20%5BEND%202%20END%5D/dataset/kaggle_diabetes.csv')

In [366]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0               2      138             62             35        0  33.6   
1               0       84             82             31      125  38.2   
2               0      145              0              0        0  44.2   
3               0      135             68             42      250  42.3   
4               1      139             62             41      480  40.7   
...           ...      ...            ...            ...      ...   ...   
1995            2       75             64             24       55  29.7   
1996            8      179             72             42      130  32.7   
1997            6       85             78              0        0  31.2   
1998            0      129            110             46      130  67.1   
1999            2       81             72             15       76  30.1   

      DiabetesPedigreeFunction  Age  Outcome  
0                        0.127   47        1  
1                        0.233   23        0  
2                        0.630   31        1  
3                        0.365   24        1  
4                        0.536   21        0  
...                        ...  ...      ...  
1995                     0.370   33        0  
1996                     0.719   36        1  
1997                     0.382   42        0  
1998                     0.319   26        1  
1999                     0.547   25        0  

[2000 rows x 9 columns]

In [370]:
df.loc[df['BMI']==0,'BMI']=np.nan

In [371]:
df.loc[df['SkinThickness']==0,'SkinThickness']=np.nan

In [372]:
df.isnull().sum()

Pregnancies                   0
Glucose                       0
BloodPressure                 0
SkinThickness               573
Insulin                       0
BMI                          28
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

In [375]:
from sklearn.impute import KNNImputer
kn=KNNImputer(n_neighbors=3)
kn.fit_transform(df)

array([[2.00e+00, 1.38e+02, 6.20e+01, ..., 1.27e-01, 4.70e+01, 1.00e+00],
       [0.00e+00, 8.40e+01, 8.20e+01, ..., 2.33e-01, 2.30e+01, 0.00e+00],
       [0.00e+00, 1.45e+02, 0.00e+00, ..., 6.30e-01, 3.10e+01, 1.00e+00],
       ...,
       [6.00e+00, 8.50e+01, 7.80e+01, ..., 3.82e-01, 4.20e+01, 0.00e+00],
       [0.00e+00, 1.29e+02, 1.10e+02, ..., 3.19e-01, 2.60e+01, 1.00e+00],
       [2.00e+00, 8.10e+01, 7.20e+01, ..., 5.47e-01, 2.50e+01, 0.00e+00]])

In [376]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [377]:
from sklearn.linear_model import LogisticRegression
lgr = LogisticRegression()

In [378]:
lgr.fit(x_train,y_train)

c:\Users\bhagy\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [380]:
lgr.score(x_test,y_test)

0.786

In [383]:
from sklearn.metrics import confusion_matrix

In [385]:
confusion_matrix(y_test,lgr.predict(x_test))

array([[290,  30],
       [ 77, 103]])

In [386]:
with open('model.pickle','wb') as model_file:
    pickle.dump(lgr,model_file)